## NUMPY

Disini kita akan memplejari mengenai numpy

In [1]:
import numpy as np
np.__version__

'1.23.2'

In [2]:
gpas_list = [4,5,6]

In [3]:
gpas_list.append(4)

In [4]:
gpas_list

[4, 5, 6, 4]

In [5]:
gpas_list.insert(1, "belum ada")
gpas_list

[4, 'belum ada', 5, 6, 4]

In [6]:
gpas_list.pop(1)

'belum ada'

In [7]:
gpas_list

[4, 5, 6, 4]

## NumPy Array

In [8]:
gpas = np.array(gpas_list)

In [9]:
gpas.dtype

dtype('int32')

In [10]:
gpas.size

4

## Study Log

In [11]:
#kita akan membuat array yang isinya 100
study_minutes = np.zeros(100, np.uint16) #np.unit16 digunakan supaya jadi integer
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [12]:
%whos # dengan begitu bisa menghemat 

No variables match your requested type.


## Array Multidimensi

In [13]:
students_gpas = np.array([
    [4.0,3.3,3.5,4.0],
    [2.96,3.92,4.0,4.0],
    [3.2,3.8,4.0,4.0]
],np.float16) #kenapa float karena indeks prestasi memiliki angka dibelakang koma
students_gpas

array([[4.  , 3.3 , 3.5 , 4.  ],
       [2.96, 3.92, 4.  , 4.  ],
       [3.2 , 3.8 , 4.  , 4.  ]], dtype=float16)

In [14]:
students_gpas.ndim # mengecek jumlah dimensi

2

In [15]:
students_gpas.shape # mengecek bentuk array

(3, 4)

In [16]:
students_gpas[2] #indexing atau mengakses data tersebut

array([3.2, 3.8, 4. , 4. ], dtype=float16)

In [17]:
students_gpas[2][1] # indexing didalam array

3.8

## Array Indexing (Study Log MultiDimensi)

In [18]:
#convert jadi 2 dimentsi
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])
study_minutes.shape

(2, 100)

In [19]:
study_minutes[1][0] = 60 # mengisi array
study_minutes

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [60,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0]], dtype=uint16)

In [20]:
rand = np.random.RandomState(42) # mengisi array dengan nilai random
fake_log = rand.randint(30,180, size = 100, dtype=np.uint16) # minimal 30 max 180
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [21]:
[fake_log[1],fake_log[21]] # indexing array dua angka yang ini jadi list

[122, 160]

In [22]:
fake_log[[1,21]] #bedanya yang ini jadi array

array([122, 160], dtype=uint16)

In [23]:
index = np.array([
    [1,21],
    [1,2]
])
fake_log[index]

array([[122, 160],
       [122, 128]], dtype=uint16)

In [24]:
study_minutes = np.append(study_minutes,[fake_log])
study_minutes #bisa memasukkan nilai array dengan nilai random

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  60,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [ ]:
study_minutes

## Demo Slicing Array

In [28]:
practice =np.arange(42)
practice.shape = (7,6)
practice # membuat array 7 * 6 tidak bisa asal asalan

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [31]:
practice[2,1]

13

In [32]:
practice[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
practice[2:5, 3]

array([15, 21, 27])

In [35]:
practice[2:5, 3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

## COPY AND VIEW

In [41]:
practice_list = [1,2,3]
practice_list_copy = practice_list[:]
practice_list, practice_list_copy
practice_list_copy[0] = 12345
practice_list, practice_list_copy

([1, 2, 3], [12345, 2, 3])

In [43]:
not_copied = practice[:]
not_copied[0,0] = 12345
practice,not_copied

(array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]))

In [44]:
print(practice.base)

None


In [46]:
print(not_copied.base)

[[12345     1     2     3     4     5]
 [    6     7     8     9    10    11]
 [   12    13    14    15    16    17]
 [   18    19    20    21    22    23]
 [   24    25    26    27    28    29]
 [   30    31    32    33    34    35]
 [   36    37    38    39    40    41]]


In [47]:
not_copied.base is practice

True

In [48]:
not_copied.base is practice_list

False

## Aljabar Linear

In [49]:
#Menentukan harga tiap item
orders = np.array([
    [2,0,0,0],
    [1,0,2,4],
    [1,2,1,0],
    [4,6,0,2]
])

totals = np.array([
    20000,32000,20000,61000
])

prices = np.linalg.solve(orders,totals)
prices

array([10000.,  2500.,  5000.,  3000.])

In [50]:
orders @ prices # untuk mengetahui apakah benar perhitungannya

array([20000., 32000., 20000., 61000.])

## Fungsi Universal

In [55]:
a,b = np.split(np.arange(1,11),2)
a,b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [56]:
a+b

array([ 7,  9, 11, 13, 15])

In [57]:
a-b

array([-5, -5, -5, -5, -5])

In [58]:
a*b

array([ 6, 14, 24, 36, 50])

In [59]:
b-a

array([5, 5, 5, 5, 5])

In [60]:
a + 3

array([4, 5, 6, 7, 8])

In [61]:
a + np.repeat(2,5)

array([3, 4, 5, 6, 7])

In [62]:
x1= np.arange(9.0).reshape((3,3))
x2 = np.arange(3.0)
x1,x2

(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 array([0., 1., 2.]))

In [63]:
np.add(x1,x2) # untuk menambahkan array 

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [64]:
x1+x2

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

## Operasi Matriks Lainnya

In [67]:
study_less = study_minutes[(study_minutes <60)&(study_minutes >0)]
study_less

array([44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52, 31,
       57, 37, 58], dtype=uint16)

In [68]:
np.add.reduce(study_less)

909

In [69]:
np.sum(study_less)

909

In [70]:
np.sum(study_minutes)

10259